<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Admin;
use Illuminate\Support\Facades\DB;
use App\Models\Supplier;
use Illuminate\Support\Str;

class SupplierSeeder extends Seeder
{
    public function run()
    {
        // Sample manufacturing company data
        $manufacturingCompanies = [
            // Previous companies
            [
                'name' => 'ABC Manufacturing',
                'email' => 'abc@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.abcmanufacturing.com',
                'mobile_primary' => '1234567890',
                'address' => '123 Manufacturing Street',
                'city' => 'Manufactureville',
                'country' => 'Countryland',
                'state' => 'Stateland',
                'zip' => '12345',
                'contact_person_name' => 'John Doe',
                'contact_person_email' => 'john.doe@example.com',
                'contact_person_phone' => '9876543210',
                'business_type' => 'Manufacturing',
                'business_registration_number' => 'ABC123456',
                'company_info' => 'We are a leading manufacturing company specializing in...',
                'instagram' => 'https://www.instagram.com/abcmanufacturing',
                'facebook' => 'https://www.facebook.com/abcmanufacturing',
                'twitter' => 'https://twitter.com/abcmanufacturing',
                'linkedin' => 'https://www.linkedin.com/company/abcmanufacturing',
                'about' => 'ABC Manufacturing is committed to delivering high-quality...',
                'established_year' => 1990,
            ],
            [
                'name' => 'XYZ Industries',
                'email' => 'xyz@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.xyzindustries.com',
                'mobile_primary' => '9876543210',
                'address' => '456 Industry Avenue',
                'city' => 'Industrial City',
                'country' => 'Manufactureland',
                'state' => 'Stateland',
                'zip' => '54321',
                'contact_person_name' => 'Jane Smith',
                'contact_person_email' => 'jane.smith@example.com',
                'contact_person_phone' => '1234567890',
                'business_type' => 'Manufacturing',
                'business_registration_number' => 'XYZ789012',
                'company_info' => 'XYZ Industries is a trusted name in the manufacturing industry...',
                'instagram' => 'https://www.instagram.com/xyzindustries',
                'facebook' => 'https://www.facebook.com/xyzindustries',
                'twitter' => 'https://twitter.com/xyzindustries',
                'linkedin' => 'https://www.linkedin.com/company/xyzindustries',
                'about' => 'At XYZ Industries, we take pride in our commitment to innovation...',
                'established_year' => 1985,
            ],
            // Additional manufacturing companies
            [
                'name' => 'EcoTech Plastics',
                'email' => 'ecotech@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.ecotechplastics.com',
                'mobile_primary' => '9871234560',
                'address' => '789 Recycle Road',
                'city' => 'Eco City',
                'country' => 'Eco Country',
                'state' => 'Green State',
                'zip' => '67890',
                'contact_person_name' => 'Michael Green',
                'contact_person_email' => 'michael.green@example.com',
                'contact_person_phone' => '5678901234',
                'business_type' => 'Plastics Manufacturing',
                'business_registration_number' => 'ECO567890',
                'company_info' => 'EcoTech Plastics is dedicated to sustainable plastic production...',
                'instagram' => 'https://www.instagram.com/ecotechplastics',
                'facebook' => 'https://www.facebook.com/ecotechplastics',
                'twitter' => 'https://twitter.com/ecotechplastics',
                'linkedin' => 'https://www.linkedin.com/company/ecotechplastics',
                'about' => 'We specialize in eco-friendly plastic solutions for a greener future...',
                'established_year' => 2005,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'MetalCraft Innovations',
                'email' => 'metalcraft@example.com',
                
                'website' => 'https://www.metalcraftinnovations.com',
                'mobile_primary' => '8765432109',
                'address' => '101 Steel Avenue',
                'city' => 'Metalville',
                'country' => 'Steeland',
                'state' => 'Metal State',
                'zip' => '54321',
                'contact_person_name' => 'Samantha Steel',
                'contact_person_email' => 'samantha.steel@example.com',
                'contact_person_phone' => '1098765432',
                'business_type' => 'Metal Fabrication',
                'business_registration_number' => 'MET123456',
                'company_info' => 'MetalCraft Innovations excels in custom metal fabrication...',
                'instagram' => 'https://www.instagram.com/metalcraftinnovations',
                'facebook' => 'https://www.facebook.com/metalcraftinnovations',
                'twitter' => 'https://twitter.com/metalcraftinnovations',
                'linkedin' => 'https://www.linkedin.com/company/metalcraftinnovations',
                'about' => 'Your trusted partner for precision metal solutions...',
                'established_year' => 1998,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'TechPro Electronics',
                'email' => 'techpro@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.techproelectronics.com',
                'mobile_primary' => '7654321098',
                'address' => '123 Circuit Road',
                'city' => 'ElectroniCity',
                'country' => 'Techland',
                'state' => 'Innovate State',
                'zip' => '43210',
                'contact_person_name' => 'David Circuit',
                'contact_person_email' => 'david.circuit@example.com',
                'contact_person_phone' => '9876543210',
                'business_type' => 'Electronics Manufacturing',
                'business_registration_number' => 'TECH543210',
                'company_info' => 'TechPro Electronics leads the way in electronic product manufacturing...',
                'instagram' => 'https://www.instagram.com/techproelectronics',
                'facebook' => 'https://www.facebook.com/techproelectronics',
                'twitter' => 'https://twitter.com/techproelectronics',
                'linkedin' => 'https://www.linkedin.com/company/techproelectronics',
                'about' => 'Your partner for cutting-edge electronic solutions...',
                'established_year' => 2002,
            ],
            [
                'name' => 'SolarTech Solutions',
                'email' => 'solartech@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.solartechsolutions.com',
                'mobile_primary' => '8765432101',
                'address' => '456 Solar Street',
                'city' => 'Solarville',
                'country' => 'Solarland',
                'state' => 'Green Energy State',
                'zip' => '56789',
                'contact_person_name' => 'Sarah Solar',
                'contact_person_email' => 'sarah.solar@example.com',
                'contact_person_phone' => '1098765432',
                'business_type' => 'Solar Panel Manufacturing',
                'business_registration_number' => 'SOLAR567890',
                'company_info' => 'SolarTech Solutions harnesses the power of the sun...',
                'instagram' => 'https://www.instagram.com/solartechsolutions',
                'facebook' => 'https://www.facebook.com/solartechsolutions',
                'twitter' => 'https://twitter.com/solartechsolutions',
                'linkedin' => 'https://www.linkedin.com/company/solartechsolutions',
                'about' => 'Bringing sustainable energy to the world, one panel at a time...',
                'established_year' => 2009,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'Textile World Inc.',
                'email' => 'textile@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.textileworldinc.com',
                'mobile_primary' => '9876543210',
                'address' => '789 Fabric Lane',
                'city' => 'Textileville',
                'country' => 'Fabricland',
                'state' => 'Fiber State',
                'zip' => '12345',
                'contact_person_name' => 'Emily Fabric',
                'contact_person_email' => 'emily.fabric@example.com',
                'contact_person_phone' => '9876543210',
                'business_type' => 'Textile Manufacturing',
                'business_registration_number' => 'TEXTILE123456',
                'company_info' => 'Textile World Inc. weaves the fabric of your dreams...',
                'instagram' => 'https://www.instagram.com/textileworldinc',
                'facebook' => 'https://www.facebook.com/textileworldinc',
                'twitter' => 'https://twitter.com/textileworldinc',
                'linkedin' => 'https://www.linkedin.com/company/textileworldinc',
                'about' => 'Creating exquisite textiles for a world of elegance...',
                'established_year' => 1995,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'FoodTech Innovations',
                'email' => 'foodtech@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.foodtechinnovations.com',
                'mobile_primary' => '7654321098',
                'address' => '123 Culinary Avenue',
                'city' => 'Foodieville',
                'country' => 'Foodland',
                'state' => 'Gourmet State',
                'zip' => '43210',
                'contact_person_name' => 'Jessica Chef',
                'contact_person_email' => 'jessica.chef@example.com',
                'contact_person_phone' => '9876543210',
                'business_type' => 'Food Processing',
                'business_registration_number' => 'FOODTECH543210',
                'company_info' => 'FoodTech Innovations revolutionizes the culinary world...',
                'instagram' => 'https://www.instagram.com/foodtechinnovations',
                'facebook' => 'https://www.facebook.com/foodtechinnovations',
                'twitter' => 'https://twitter.com/foodtechinnovations',
                'linkedin' => 'https://www.linkedin.com/company/foodtechinnovations',
                'about' => 'Serving up innovation and flavor in every bite...',
                'established_year' => 2010,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'GreenBuild Constructions',
                'email' => 'greenbuild@example.com',
                'password' => bcrypt('password123'),
                'website' => 'https://www.greenbuildconstructions.com',
                'mobile_primary' => '8765432101',
                'address' => '456 Eco Lane',
                'city' => 'Ecoland',
                'country' => 'Greenland',
                'state' => 'Eco State',
                'zip' => '56789',
                'contact_person_name' => 'Michael Eco',
                'contact_person_email' => 'michael.eco@example.com',
                'contact_person_phone' => '1098765432',
                'business_type' => 'Construction',
                'business_registration_number' => 'GREENBUILD567890',
                'company_info' => 'GreenBuild Constructions builds a sustainable future...',
                'instagram' => 'https://www.instagram.com/greenbuildconstructions',
                'facebook' => 'https://www.facebook.com/greenbuildconstructions',
                'twitter' => 'https://twitter.com/greenbuildconstructions',
                'linkedin' => 'https://www.linkedin.com/company/greenbuildconstructions',
                'about' => 'Constructing eco-friendly structures for a greener tomorrow...',
                'established_year' => 2008,
                'password' => bcrypt('password'),
            ],
            [
                'name' => 'TechSolutions Inc.',
                'email' => 'techsolutions@example.com',
                'password' => bcrypt('tech123'),
                'website' => 'https://www.techsolutionsinc.com',
                'mobile_primary' => '9876543210',
                'address' => '123 Tech Street',
                'city' => 'Techville',
                'country' => 'Techland',
                'state' => 'Tech State',
                'zip' => '43210',
                'contact_person_name' => 'John Tech',
                'contact_person_email' => 'john.tech@example.com',
                'contact_person_phone' => '1234567890',
                'business_type' => 'Technology Services',
                'business_registration_number' => 'TECH98765',
                'company_info' => 'TechSolutions Inc. provides cutting-edge tech solutions...',
                'instagram' => 'https://www.instagram.com/techsolutionsinc',
                'facebook' => 'https://www.facebook.com/techsolutionsinc',
                'twitter' => 'https://twitter.com/techsolutionsinc',
                'linkedin' => 'https://www.linkedin.com/company/techsolutionsinc',
                'about' => 'Your partner in technology innovation and excellence...',
                'established_year' => 2005,
            ],
            [
                'name' => 'FashionFusion Boutique',
                'email' => 'fashionfusion@example.com',
                'password' => bcrypt('fashion456'),
                'website' => 'https://www.fashionfusionboutique.com',
                'mobile_primary' => '8765432105',
                'address' => '789 Chic Avenue',
                'city' => 'Styletown',
                'country' => 'Fashionland',
                'state' => 'Fashion State',
                'zip' => '54325',
                'contact_person_name' => 'Amanda Style',
                'contact_person_email' => 'amanda.style@example.com',
                'contact_person_phone' => '1054321098',
                'business_type' => 'Fashion Retail',
                'business_registration_number' => 'FASHION789',
                'company_info' => 'FashionFusion Boutique offers the latest in fashion trends...',
                'instagram' => 'https://www.instagram.com/fashionfusionboutique',
                'facebook' => 'https://www.facebook.com/fashionfusionboutique',
                'twitter' => 'https://twitter.com/fashionfusion',
                'linkedin' => 'https://www.linkedin.com/company/fashionfusionboutique',
                'about' => 'Your go-to destination for stylish and trendy clothing...',
                'established_year' => 2012,
            ],

            [
                'name' => 'EcoFriendly Landscapes',
                'email' => 'ecofriendlylandscapes@example.com',
                'password' => bcrypt('landscape789'),
                'website' => 'https://www.ecofriendlylandscapes.com',
                'mobile_primary' => '7654321099',
                'address' => '567 Greenery Lane',
                'city' => 'Natureville',
                'country' => 'EcoLand',
                'state' => 'Green State',
                'zip' => '54323',
                'contact_person_name' => 'Emily Green',
                'contact_person_email' => 'emily.green@example.com',
                'contact_person_phone' => '1098765432',
                'business_type' => 'Landscaping Services',
                'business_registration_number' => 'ECO567',
                'company_info' => 'EcoFriendly Landscapes transforms outdoor spaces into eco-havens...',
                'instagram' => 'https://www.instagram.com/ecofriendlylandscapes',
                'facebook' => 'https://www.facebook.com/ecofriendlylandscapes',
                'twitter' => 'https://twitter.com/ecolandscapes',
                'linkedin' => 'https://www.linkedin.com/company/ecofriendlylandscapes',
                'about' => 'Bringing nature',
                'established_year' => 2009,
            ],
            
            // Company 5
            [
                'name' => 'GreenTech Solutions',
                'email' => 'greentech@example.com',
                'password' => bcrypt('greentech789'),
                'website' => 'https://www.greentechsolutions.com',
                'mobile_primary' => '9876543215',
                'address' => '234 Eco Boulevard',
                'city' => 'GreenTech City',
                'country' => 'EcoLand',
                'state' => 'Green State',
                'zip' => '54321',
                'contact_person_name' => 'David Green',
                'contact_person_email' => 'david.green@example.com',
                'contact_person_phone' => '9876543215',
                'business_type' => 'Green Technology',
                'business_registration_number' => 'GREENTECH234',
                'company_info' => 'GreenTech Solutions specializes in eco-friendly tech innovations...',
                'instagram' => 'https://www.instagram.com/greentechsolutions',
                'facebook' => 'https://www.facebook.com/greentechsolutions',
                'twitter' => 'https://twitter.com/greentech',
                'linkedin' => 'https://www.linkedin.com/company/greentechsolutions',
                'about' => 'Pioneering green technology for a sustainable future...',
                'established_year' => 2015,
            ],
            
            // Add more manufacturing companies here
        ];
        

        foreach ($manufacturingCompanies as $company) {
            $company['slug'] = Str::slug($company['name']); // Generate a slug from the company name
            DB::table('suppliers')->insert($company);
        }
    }
}